Repository laterpay/supertab-browser, pull requests merged in 2024-08, with the labels that each got.

#65 feat: Expose connected subscription offerings
  __snapshots__/Supertab.test.ts.snap
  src/index.ts
Labels: Ready For Review, 1 min review

#66 fix: Refactor connected subscription logic to fix TypeScript issue
  src/index.ts
Labels: Ready For Review, 1 min review

#67 feat: use @getsupertab scope and host on npm
  .circleci/config.yml
  .npmrc
  README.md
  Supertab.test.ts
  __snapshots__/Supertab.test.ts.snap
  bun.lockb
  bunfig.toml
  package.json
  src/index.ts
  src/mocks/server.ts
  tsup.prod.config.ts
  tsup.sbx.config.ts
  tsup.stg.config.ts
Labels: 10 min review

#68 Switch back to Hydra auth endpoint STG
  tsup.stg.config.ts
Labels: 1 min review, single-line

#63 Switch to supertab.co domain on SBX
  .env.local
  .env.test
  src/mocks/server.ts
  tsup.sbx.config.ts
Labels: 1 min review
